MOUSEKEY_ENABLE = yes
BOOTMAGIC_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
MIDI_ENABLE = no
AUDIO_ENABLE = yes
AUTO_SHIFT_ENABLE = no
UNICODE_ENABLE = no
TAP_DANCE_ENABLE = yes
KEY_LOCK_ENABLE = yes

SRC += $(USER_PATH)/liljaylj.c
