#pragma once

#define ORYX_CONFIGURATOR

#define I2C1_CLOCK_SPEED 400000

#define RGB_MATRIX_DEFAULT_SPD 60
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_JELLYBEAN_RAINDROPS

// #ifdef AUDIO_ENABLE
// #   define STARTUP_SONG SONG(PLANCK_SOUND)
// // #   define STARTUP_SONG SONG(NO_SOUND)
// #endif
